package cli

import (
	"fmt"
	"os"
	"path/filepath"
)

// GenerateRedirectScript creates a redirect script template with commented instructions
func GenerateRedirectScript(scriptPath, command string) error {
	// Check if file already exists
	if _, err := os.Stat(scriptPath); err == nil {
		return fmt.Errorf("script already exists at %s (will not overwrite)", scriptPath)
	}

	// Create parent directories if they don't exist
	dir := filepath.Dir(scriptPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Generate script content
	template := generateScriptTemplate(command)

	// Write script file
	if err := os.WriteFile(scriptPath, []byte(template), 0755); err != nil {
		return fmt.Errorf("failed to write script file: %w", err)
	}

	return nil
}

func generateScriptTemplate(command string) string {
	return fmt.Sprintf(`#!/bin/bash
# Redirect script for: %s
# Generated by ribbin
#
# This script is executed instead of the original %s binary.
# You can modify arguments, environment, or add custom logic before calling the original.

# Environment variables provided by ribbin:
#   RIBBIN_ORIGINAL_BIN - Path to original binary (e.g., /usr/bin/%s.ribbin-original)
#   RIBBIN_COMMAND      - Command name (e.g., "%s")
#   RIBBIN_CONFIG       - Path to ribbin.jsonc that triggered this redirect
#   RIBBIN_ACTION       - Always "redirect"

# Example 1: Call original command with all arguments
# exec "$RIBBIN_ORIGINAL_BIN" "$@"

# Example 2: Add custom flags or modify behavior
# exec "$RIBBIN_ORIGINAL_BIN" --custom-flag "$@"

# Example 3: Add environment variables
# export CUSTOM_VAR=value
# exec "$RIBBIN_ORIGINAL_BIN" "$@"

# Example 4: Conditional logic
# if [[ "$1" == "build" ]]; then
#     echo "Running custom build process"
#     exec "$RIBBIN_ORIGINAL_BIN" build --production "$@"
# else
#     exec "$RIBBIN_ORIGINAL_BIN" "$@"
# fi

# TODO: Customize this script for your needs
# Remember to use 'exec' to replace the current process
exec "$RIBBIN_ORIGINAL_BIN" "$@"
`, command, command, command, command)
}
